const data = [
  {
    id: "0",
    image: "/images/CarolineForbes.png",
    name: "Caroline Forbes",
    belt_grade: "Black 2nd Dan",
    coach_notes: [
      {
        coach_id: "123",
        date: "15/05/23",
        note: "Good work",
        speed: "",
        stamina: "",
        flexibility: "",
        agility: "",
        reflex: "",
      },
    ],
  },
  {
    id: "1",
    image: "/images/ElijahMikealson.png",
    name: "Elijah Mikealson",
    belt_grade: "Black 2nd Dan",
    coach_notes: [
      {
        coach_id: "123",
        date: "15/05/23",
        note: "Good work",
        speed: "",
        stamina: "",
        flexibility: "",
        agility: "",
        reflex: "",
      },
    ],
  },
  {
    id: "2",
    image: "/images/KlausMikealson.png",
    name: "Klaus Mikealson",
    belt_grade: "Black 2nd Dan",
    coach_notes: [
      {
        coach_id: "123",
        date: "15/05/23",
        note: "Good work",
        speed: "",
        stamina: "",
        flexibility: "",
        agility: "",
        reflex: "",
      },
    ],
  },
  {
    id: "3",
    image: "/images/KolMikealson.png",
    name: "Kol Mikealson",
    belt_grade: "Black 2nd Dan",
    coach_notes: [
      {
        coach_id: "123",
        date: "15/05/23",
        note: "Good work",
        speed: "",
        stamina: "",
        flexibility: "",
        agility: "",
        reflex: "",
      },
    ],
  },
  {
    id: "4",
    image: "/images/FinMikealson.png",
    name: "Fin Mikealson",
    belt_grade: "Black 2nd Dan",
    coach_notes: [
      {
        coach_id: "123",
        date: "15/05/23",
        note: "Good work",
        speed: "",
        stamina: "",
        flexibility: "",
        agility: "",
        reflex: "",
      },
    ],
  },
  {
    id: "5",
    image: "/images/RebekhaMikealson.png",
    name: "Rebekha Mikealson",
    belt_grade: "Black 2nd Dan",
    coach_notes: [
      {
        coach_id: "123",
        date: "15/05/23",
        note: "Good work",
        speed: "",
        stamina: "",
        flexibility: "",
        agility: "",
        reflex: "",
      },
    ],
  },
  {
    id: "6",
    image: "/images/HopeMikealson.png",
    name: "Hope Mikealson",
    belt_grade: "Black 2nd Dan",
    coach_notes: [
      {
        coach_id: "123",
        date: "15/05/23",
        note: "Good work",
        speed: "",
        stamina: "",
        flexibility: "",
        agility: "",
        reflex: "",
      },
    ],
  },
  {
    id: "7",
    image: "/images/HayleyMikealson.png",
    name: "Hayley Mikealson",
    belt_grade: "Black 2nd Dan",
    coach_notes: [
      {
        coach_id: "123",
        date: "15/05/23",
        note: "Good work",
        speed: "",
        stamina: "",
        flexibility: "",
        agility: "",
        reflex: "",
      },
    ],
  },
  {
    id: "8",
    image: "/images/MarshallMikealson.png",
    name: "Marshall Mikealson",
    belt_grade: "Black 2nd Dan",
    coach_notes: [
      {
        coach_id: "123",
        date: "15/05/23",
        note: "Good work",
        speed: "",
        stamina: "",
        flexibility: "",
        agility: "",
        reflex: "",
      },
    ],
  },
  {
    id: "9",
    image: "/images/FreyaMikealson.png",
    name: "Freya Mikealson",
    belt_grade: "Black 2nd Dan",
    coach_notes: [
      {
        coach_id: "123",
        date: "15/05/23",
        note: "Good work",
        speed: "",
        stamina: "",
        flexibility: "",
        agility: "",
        reflex: "",
      },
    ],
  },
  
];

export default data;
